### ISSUE TITLE
Other subview frame changes

### ISSUE THREAD

**Issue by vinayakparmar92** [andreamazz/AMPopTip#126]
When I show popover, a subview which is not hidden but out of screen bounds shows up(its frame changes). I need that subview to be out of screen bounds for some animation purpose. Any idea why this might happen?

**Comment by andreamazz** [comment]
Hard to tell, can you reproduce the issue in any way in a sample project to share?

**Comment by vinayakparmar92** [comment]
Sure. Have a look at [this](https://github.com/vinayakparmar92/TestProj) project. It is easily reproducible. It will reset the frame of the moved subview to original position

**Comment by vinayakparmar92** [comment]
@andreamazz Any updates on this?

**Comment by andreamazz** [comment]
Not yet, sorry, I'm swamped at work, I can't seem to find time to check this, sorry about that. I'll try to make time this weekend

**Comment by vinayakparmar92** [comment]
No problem. Please do update here. Thank you :)

**Comment by andreamazz** [comment]
Ok, I took a looka t the sample project. The issue is not related to this library. 
You are using autolayout, when a new view is added (the poptip) the rules are enforced. 
When using autolaout you shouldn't manually touch the view's frame, you should either drop AO for that view, and handle it manually, or keep AO and use transformations instead:
```swift
      tempView.transform = CGAffineTransform(translationX: 0, y: 1000)
```

**Comment by vinayakparmar92** [comment]
Wasn't aware of this. Thanks for sharing the info :)
