### ISSUE TITLE
PopTips on Views with scroll

### ISSUE THREAD

**Issue by alph0x** [andreamazz/AMPopTip#16]
When i try to use the PopTip on a Scrollable view (most in cases of 3.5") only works when the view is in the original position, when you change, the PopTip remains on that position, doesn't change even when you try to show it again...

**Comment by matheushenriquesantos** [comment]
Hi, can you show how?

**Comment by matheushenriquesantos** [comment]
Hi @andreamazz , can you show the piece of code?

**Comment by MincDev** [comment]
@andreamazz Please provide code. I have been struggling for over 2 hours with this issue. My poptip shows perfectly in the initial view of the scrollview. Anything outside of the initial view will have the poptip jump to the top part of the scrollview

**Comment by alph0x** [comment]
Hi @MincDev, this isn't a issue at all, I was just mistaken back then, remember that the frame that points the popView and the View that is going to show it, doesn't have to be the same, use the scrollView you want to pop it.

**Comment by andreamazz** [comment]
> @andreamazz Please provide code. I have been struggling for over 2 hours with this issue. My poptip shows perfectly in the initial view of the scrollview. Anything outside of the initial view will have the poptip jump to the top part of the scrollview

If I understand this correctly you want to show the tip on a scrollable view, and have the tip follow the scrolling instead of staying put, correct? Let me concoct a quick sample, BRB

**Comment by andreamazz** [comment]
[Scroll.zip](https://github.com/andreamazz/AMPopTip/files/3223340/Scroll.zip)

**Comment by MincDev** [comment]
> [Scroll.zip](https://github.com/andreamazz/AMPopTip/files/3223340/Scroll.zip)
> 
> Here. As you can see the tip is shown in the scrollview. Consider that `show` just calls `addSubview` to the view that you pass in the `in` parameter, the `from` frame is used just to adjust the position in relation to that view. Treat it as you would treat a common `UIView`

No, the problem was that if I wanted to show the tooltip and the screen has been scrolled down from the original loading state, the tooltip would display at the top, outside of the current view. As if the part of the scrollview currently being shown does not exist. However I was able to fix this issue by commenting out the following in your code. (I only commented this out, because I don't know if it may break something else, but seems to be working perfectly now)

`if (y + frame.size.height > self.containerView.bounds.size.height) { y = self.containerView.bounds.size.height - frame.size.height - self.edgeMargin; }` - Line 145 of AMpopTip.m

This part of the code didn't make sense to me as it kept on overriding my offsetBy method. Taking it out, allowed me to put the poptip anywhere I wished. However, if you know whether this may cause other issues, please let me know.

**Comment by andreamazz** [comment]
`AMPopTip.m`? 
You're still using the Objective-C version? That code is really old, you should move to the latest release, which has the appropriate `constrainInContainerView` property to skip that check.

**Comment by MincDev** [comment]
> `AMPopTip.m`?
> You're still using the Objective-C version? That code is really old, you should move to the latest release, which has the appropriate `constrainInContainerView` property to skip that check.

Ah, thanks mate! This all makes perfect sense now. :)
