### ISSUE TITLE
Causes issue when using inside another view except the root view

### ISSUE THREAD

**Issue by arpitjain03** [andreamazz/AMPopTip#183]
When I try to use PopTip on a button inside a view, I got the framing issues as shown.

![Simulator Screen Shot - iPhone XR - 2019-03-28 at 17 17 46](https://user-images.githubusercontent.com/30592234/55155739-26313900-517e-11e9-9a66-1a5c3f214c86.png)

**Comment by andreamazz** [comment]
You're probably giving relative coordinates instead of absolute ones. This is a basic UIView at its heart, so the basic UIView consideration about subviews and view's frame apply. Either add the tip to the button's subview, or [adjust the frame](https://developer.apple.com/documentation/uikit/uiview/1622442-convert) to reflect the poptip container

**Comment by arpitjain03** [comment]
I tried the same but somehow, its not getting proper framing in subviews

**Comment by andreamazz** [comment]
Check the frame you are passing, the `show` just does an `addSubview`

**Comment by ManishaJoshi-mj** [comment]
Just pass the outlet of view in which you have  the button. 
For example lets say the outlet of yellow view(as per the screenshot) is displayAlertView. 
Then call the method to show as :- 
 **popTip.show(text: strTextToDisplay, direction: .up, maxWidth: 200, in: displayAlertView, from:button.frame)**

**Comment by arpitjain03** [comment]
@ManishaJoshi-mj  Thanks for the help.
