### ISSUE TITLE
NavigationBarItemFrame

### ISSUE THREAD

**Issue by umekun123** [andreamazz/AMPopTip#24]
This is super cool library, thanks for making it.

It would be awesome if you could add getting frames for navigation bar items like right navibar button frame.

Is there any way to get the frame of self.navigationItem.leftBarButtonItem at the moment?  I've been trying to find out the way, but no luck yet.

**Comment by andreamazz** [comment]
Hi @umekun123 
There is no 'safe' way that I know of for getting the barbutton's frame. You can use KVC to get the 'view' property of the button, but it might be considered as private API usage (although is not likely). 
A safer way is to provide your own custom button, in that case you have access to the `customView`'s frame.  
It's not unreasonable to 'guess' the position of the button though. Since you know the navigation bar's height, you can easily compute the button's position.

**Comment by umekun123** [comment]
Thanks for your sincere and valuable reply.  I look into the best way to solve my issue, thanks for your advice!

**Comment by andreamazz** [comment]
Closing this one. Feel free to reopen if needed. :+1:

**Comment by acegreen** [comment]
@andreamazz I tried the following 

 CGRect(x: view.frame.width - 28, y: self.navigationController!.navigationBar.frame.height, width: 1, height: 1)

but the tip appears below the expected height of the navigationBar. 

![simulator screen shot dec 11 2015 2 24 52 pm](https://cloud.githubusercontent.com/assets/10794609/11753462/34169170-a013-11e5-88ae-d3f74971db78.png)

**Comment by andreamazz** [comment]
inside a navigation controller with an opaque navigation bar, you root view controller's view frame starts at 0. So, use 0 instead of the navbar's height

**Comment by acegreen** [comment]
Thanks
