### ISSUE TITLE
tableView on popView can't respond touch.

### ISSUE THREAD

**Issue by meilulu** [andreamazz/AMPopTip#67]
UITableView *tableView = [[UITableView alloc] initWithFrame:CGRectMake(0, 0, 100, 200)];
    tableView.delegate = self;
    tableView.dataSource = self;
    [tableView registerClass:[UITableViewCell class] forCellReuseIdentifier:@"cell"];
    [customView addSubview:tableView];
[self.popTip showCustomView:customView direction:AMPopTipDirectionDown inView:self.view fromFrame:sender.frame];

**Comment by andreamazz** [comment]
Hi @meilulu 
That's probably due to the tap handler that dismisses the poptip.
The library is intended mostly for giving feedback and hints to the user, having a table inside might be a littl eoverkill.
Anyhoo, you can try to set the gestureRecognizer as disabled.

**Comment by HarshalIndiJoshi** [comment]
Hello, 
I'm also having the same issue. @meilulu  can you please tell me what is the solution you implemented? Since you have closed this question I assume you don't have this issue anymore. 
@andreamazz  Even though you are awaiting feedback from @meilulu  I still wanna ask you if you have found the solution for this.

Thanks in advance.
