### ISSUE TITLE
AM_POPTIP_EXTENSION not working

### ISSUE THREAD

**Issue by vinayak-parmar-cf** [andreamazz/AMPopTip#96]
Tried using `AM_POPTIP_EXTENSION ` macro in Share extension target. Still if shows error for API not available for Extensions. Any help?

**Comment by andreamazz** [comment]
Hey @vinayak-parmar-cf 
It's hard to debug with nothing to work on. How did you declare the macro?

**Comment by vinayak-parmar-cf** [comment]
I have declared them in Preprocessor Macros form Build settings and Active Compilation conditions. I am using other Swift libs also in Objective C project

**Comment by vinayak-parmar-cf** [comment]
The compilation fails. I get error at the same line. Since `[UIApplication sharedApplication]` is not available for Extensions. Basically it not able to detect the Macro. I think you will have to configure your `GCC_PREPROCESSOR_DEFINITIONS` in .xcconfig file. Have you tried using the project as a pod?

**Comment by andreamazz** [comment]
Yeah, I use it as a Pod, but never in an extension. Come to think of it, it makes sense, the project that need that macro is the Pods project...

Let me look for a workaround... there's `NS_EXTENSION_UNAVAILABLE_IOS`, but it marks a whole method as unavailable, not what I want.

**Comment by andreamazz** [comment]
No, scratch that, it works also in a #if 
Ok, I'll fix it right away

**Comment by andreamazz** [comment]
There, check out version `1.4.1`

**Comment by vinayak-parmar-cf** [comment]
Will check it. Thank you so much. Even AFNetworking were using this type of Macro. Now they have switched to `NS_EXTENSION_UNAVAILABLE_IOS` thing. That seems like the solution that works OR the .xconfig thing where you can declare macro. This is how AsyncDisplayKit uses macros in .xcconfig 

`GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 $(inherited) PIN_REMOTE_IMAGE=1`

So now project will detect `PIN_REMOTE_IMAGE` when declared in build settings

**Comment by andreamazz** [comment]
Does it work?

**Comment by vinayak-parmar-cf** [comment]
Yea. Works fine now. Thank you

**Comment by shardul89** [comment]
@andreamazz I have been using AMPopTip since long in my project which has share extension support. Since I have tried to update on latest version 2.1.0 its giving error as you guys have used *UIApplication.shared* method in below mentioned function. We can't use that API for share extension. It would be great if you guys can suggest me any alternative or else I have to stick with the same old version of AMPopTip which is working fine on share extension.

open func hide(forced: Bool = false) {
    if !forced && isAnimating {
      return
    }

    layer.removeAllAnimations()

    isAnimating = true
    dismissTimer?.invalidate()
    dismissTimer = nil
    if let gestureRecognizer = tapRemoveGestureRecognizer {
      containerView?.removeGestureRecognizer(gestureRecognizer)
    }
    if let gestureRecognizer = swipeGestureRecognizer {
      containerView?.removeGestureRecognizer(gestureRecognizer)
    }

    let completion = {
      self.customView?.removeFromSuperview()
      self.customView = nil
      self.dismissActionAnimation()
      self.backgroundMask?.removeFromSuperview()
      self.removeFromSuperview()
      self.layer.removeAllAnimations()
      self.transform = .identity
      self.isAnimating = false
      self.dismissHandler?(self)
    }

    var isActive = true
    if #available(iOS 8, *) {
      isActive = UIApplication.shared.applicationState == .active
    }
    if !isActive {
      completion()
    } else {
      performExitAnimation(completion: completion)
    }
  }

**Comment by andreamazz** [comment]
Hey @shardul89 
thanks for the feedback. From what I gathered from the apple doc I thought that the `#available(iOS` would exclude that line from the extensions. I'll fix it right away.

**Comment by andreamazz** [comment]
Ok, checkout the latest commit in master for a fix, let me know if that works so I can push a new release

**Comment by andreamazz** [comment]
Ok, pushed `2.1.2`, fixed the regression.

**Comment by shardul89** [comment]
@andreamazz thanks for the quick reply. I am also working on this to work. So here is the another scenario. Our app is using Objc and swift together. And your new swift code is not completely compatible with Objc. Few of the methods are not even exposed to Objc because you have used some APIs which are only compatible with Swift. Here is the few pin points that I have seen in ur code that needs to be updated :
1. Your class name should have objc(YOUR_CLASS_NAME) declarative above your classes
```
@objc(PopTipVC)
public class PopTipVC: UIView    {
}
```
2. Your enums should have objc
```
 @objc public enum PopTipDirection {
  case up
  case down
  case left
  case right
  case none
}
```

If you don't follow above convention than the methods that uses above enums will not get exposed to objc classes. I have made one open source library called [CFAlertViewController](https://github.com/Codigami/CFAlertViewController) in Objc and than converted it to Swift 3. At that time I have faced this all issues to make it compatible with swift and Objc. Do go through its main class. You will get an idea.

I hope this helps. Do drop me a message here and I will check it once you fix this issue.

**Comment by andreamazz** [comment]
Currently the Objc compatibility was not taken in consideration by design. Some features of the new api are not available (I'm using associated enum values, which are AFAIK not supported in Objective-C). Since version 1.x is fairly stable, I'd advise sticking with that version if you need to run this alongside Objective-C

**Comment by andreamazz** [comment]
BTW, I won't be dropping support to version 1.x anytime soon
